jwt:
  secret-key: seungwoo_sns_application-2023-secretkey
  token.expired-time-ms: 2592000000

spring:
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  datasource:
    hikari:
      maximum-pool-size: 4
    url:
    username:
    password:
    platform: postgres
    driver-class-name: org.postgresql.Driver