jwt:
  secret-key: seungwoo_sns_application-2023-secretkey
  token.expired-time-ms: 2592000000

spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/sns
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver